### ISSUE TITLE
Kerning too loose for I-c pair

### ISSUE THREAD

**Issue by dtwist** [googlefonts/Pacifico#5]
I was trying Pacifica for a new client that sells ice cream. Found that kerning is off for the capital "I" and lowercase "c" in Google's hosted version of Pacifica.
![image](https://user-images.githubusercontent.com/957686/61983875-e4db5980-afb6-11e9-958b-80c58fd6959a.png)

I tested and confirmed this behavior in latest versions of FF, Safari and Chrome on Mac; Edge 18, FF and Chrome on Windows; Safari and Chrome on IOS 11 & 12; Chrome and FF on Android 7, 8 and 9.

Edge 17 and IE 11 are the only browsers that show tighter kerning.

Kerning for capital "I" and lowercase "e" are also off. Not really an issue for English, but I don't know if other languages have words with that letter pair.

**Comment by dtwist** [comment]
Closing since a copy of this issue I opened in google/fonts was responded to. https://github.com/google/fonts/issues/2121

**Comment by 5094919-lang** [comment]
gds
